### ISSUE TITLE
Typo in types on New project template screen

### ISSUE THREAD

**Issue by krishna-kashyap** [platformsh/platformsh-ui-issue-tracker#30]
**Describe the bug**
Types drop down in the the new project template screen has `Framework` and `Framwork`. They yield different results too. 

**To Reproduce**
1. Go to 'console.platform.sh'
2. Click on 'Add Project'
3. Give any name to the project
4. Click 'Next'
5. Click on the drop-down with 'All types'
6. See multiple entries for framework with different spelling

**Expected behavior**
Have a single framework type, which filters out project templates using frameworks in different languages

**Screenshots**
![Screenshot from 2019-04-02 18-43-41](https://user-images.githubusercontent.com/3992725/55405368-7f7edb00-5577-11e9-8db4-6f71976b8ae3.png)

**Comment by GuGuss** [comment]
Hi,

Thanks for reporting. This issue has been fixed.

<img width="358" alt="Capture d’écran 2019-04-12 à 14 49 21" src="https://user-images.githubusercontent.com/1927538/56068058-3f1b1c00-5d32-11e9-9da6-5b6f4ad6f4f8.png">

**Comment by GuGuss** [comment]
FYI, it's been fixed in this commit: https://github.com/platformsh/template-builder/commit/4b39e5e9cc3c52dc3b497cf87a05bf0574b48ee9#diff-546166625f648d87a005f0a03a3c9ccb
