### ISSUE TITLE
Inactive environments can't be activated from the UI

### ISSUE THREAD

**Issue by alexthunder3** [platformsh/platformsh-ui-issue-tracker#32]
**Describe the bug**
For newly created branches you can't activate the environment because "Settings" shows us the project settings instead of the environment settings. Also the environment dropdown changes to "Select environment" as if it doesn't exist/recognize the branch.

**To Reproduce**
Select an environment that is inactive, click on Settings.

**Expected behavior**
The environment settings should show up, where you can activate the environment. (the "Select environment" dropdown should show the selected branch)

**Screenshots**
Selecting inactive branch
![Screenshot from 2019-04-12 11-59-11](https://user-images.githubusercontent.com/20271194/56029412-990fe780-5d1a-11e9-8c55-24f0a437103a.png)

Clicked on Settings
![Screenshot from 2019-04-12 11-59-20](https://user-images.githubusercontent.com/20271194/56029433-a5944000-5d1a-11e9-97a6-e6d77c74ca5c.png)

This is how it should look (an already active environment where these settings can be accessed) 
![Screenshot from 2019-04-12 11-59-58](https://user-images.githubusercontent.com/20271194/56029459-af1da800-5d1a-11e9-9f5e-3680a82dea65.png)

**Comment by GuGuss** [comment]
Hi, thanks for reporting this issue.

However, I can't reproduce the issue. 

Steps:
* Create a new branch with Git.
* Push the branch with Git.
* Access the environment page on the Console from the environments list (need to select: `show inactive`) or directly via the URL: https://console.platform.sh/USER/PROJECT_ID/BRANCH_NAME.
* Click on the `Settings` link.
* Click on the `Activate` button.

@alexthunder3 Are you able to reproduce the issue?

**Comment by alexthunder3** [comment]
Clicking the "Settings" link was what reverted me back to "Select environment". So basically de-selecting my branch.
In any case, it's been gone for some time now.

Thanks, keep up the nice work!
