### ISSUE TITLE
Bulk Management of Projects, Users, Permissions

### ISSUE THREAD

**Issue by timgilmour** [platformsh/platformsh-ui-issue-tracker#4]
Allow admins to bulk edit / manage users, projects, and permissions within the new Platform.sh UI.

From PSH Slack:

```
Have you given “the bulk edit” some thoughts btw? We have +30 projects with +10 devs. It’s not an easy job on managing those access levels on each project. Some kind of “bulk” edit would be helpful for us (and other agencies as well I believe)
**Describe the solution you'd like**
A clear and concise description of what you want to happen.
```

**Comment by GuGuss** [comment]
This is a recurrent feedback that we are addressing as part of our Fleet Management initiative which we are currently working on actively. The goal is to make it easy to manage a large number of projects, teams and organizations.

However, this feature request can not be tracked as part of this UI dedicated issue tracker.
