### ISSUE TITLE
Inactive environments should be hidden by default on the project overview page

### ISSUE THREAD

**Issue by timgilmour** [platformsh/platformsh-ui-issue-tracker#9]
When viewing the branch / environment list, it would be useful to have the ability to filter out inactive environments.

**Comment by winnjewett** [comment]
This should be the default, not an option

**Comment by timgilmour** [comment]
Yes @winnjewett I agree, in addition to the filter control

**Comment by GuGuss** [comment]
Designs have been approved, and this will be implemented soon. Thanks for your feedbacks.

**Comment by GuGuss** [comment]
This issue has been solved.

![Capture d’écran 2019-03-21 à 16 08 47](https://user-images.githubusercontent.com/1927538/54739610-b5c16f80-4bf3-11e9-8640-85afa863bcfa.png)
